import { NextResponse } from 'next/server';
import puppeteer from 'puppeteer';

// Helper: Convert Markdown to HTML
const mdToHtml = (text) => {
    if (!text) return "";
    return text
        // Headers
        .replace(/^### (.*$)/gim, '<h3>$1</h3>')
        .replace(/^## (.*$)/gim, '<h2>$1</h2>')
        .replace(/^# (.*$)/gim, '<h1>$1</h1>')
        // Bold/Italic
        .replace(/\*\*(.*)\*\*/gim, '<b>$1</b>')
        .replace(/\*(.*)\*/gim, '<i>$1</i>')
        // Code Blocks
        .replace(/```([\s\S]*?)```/gim, '<pre><code>$1</code></pre>')
        // Inline Code
        .replace(/`([^`]+)`/gim, '<code>$1</code>')
        // Lists
        .replace(/^\s*-\s+(.*$)/gim, '<li>$1</li>')
        .replace(/^\s*\d+\.\s+(.*$)/gim, '<li>$1</li>')
        // Paragraphs (double newline)
        .replace(/\n\n/g, '<br><br>');
};

// Helper: Generate HTML for Course
const generateCourseHtml = (data) => {
    const modulesHtml = data.modules.map((mod, mIdx) => `
        <div class="module-page">
            <h1 class="module-title">Module ${mIdx + 1}: ${mod.title}</h1>
            ${mod.lessons.map((lesson, lIdx) => `
                <div class="lesson-section">
                    <h2 class="lesson-title">${mIdx + 1}.${lIdx + 1} ${lesson.title}</h2>
                    <div class="content">${mdToHtml(lesson.content)}</div>
                </div>
            `).join('')}
        </div>
    `).join('');

    return `
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
            body { font-family: 'Inter', sans-serif; color: #1f2937; margin: 0; padding: 40px; }
            .cover { text-align: center; height: 100vh; display: flex; flex-direction: column; justify-content: center; align-items: center; }
            .logo { width: 100px; margin-bottom: 20px; }
            h1 { color: #2563eb; }
            .cover h1 { font-size: 48px; margin: 0; }
            .cover h2 { font-size: 24px; color: #6b7280; font-weight: normal; margin-top: 10px; }
            .meta { margin-top: 40px; color: #9ca3af; }
            
            .toc { page-break-before: always; }
            .module-page { page-break-before: always; }
            .lesson-section { margin-bottom: 40px; }
            
            h1.module-title { font-size: 36px; border-bottom: 2px solid #2563eb; padding-bottom: 10px; margin-bottom: 30px; }
            h2.lesson-title { font-size: 24px; color: #1e40af; margin-top: 0; }
            
            .content { font-size: 14px; line-height: 1.6; }
            pre { background: #f3f4f6; padding: 15px; border-radius: 8px; overflow-x: auto; }
            code { font-family: monospace; color: #dc2626; }
            li { margin-bottom: 8px; }
        </style>
    </head>
    <body>
        <div class="cover">
            <h1>ACTINOVA</h1>
            <h2>${data.title}</h2>
            <div class="meta">Generated on ${new Date().toLocaleDateString()}</div>
        </div>

        <div class="toc">
            <h1>Table of Contents</h1>
            ${data.modules.map((m, i) => `
                <p><strong>Module ${i + 1}: ${m.title}</strong></p>
                ${m.lessons.map((l, j) => `<p style="margin-left:20px">${i + 1}.${j + 1} ${l.title}</p>`).join('')}
            `).join('')}
        </div>

        ${modulesHtml}
    </body>
    </html>`;
};

// Helper: Generate HTML for Lesson
const generateLessonHtml = (data) => {
    return `
    <!DOCTYPE html>
    <html>
    <head>
        <style>
            @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap');
            body { font-family: 'Inter', sans-serif; color: #1f2937; margin: 0; padding: 40px; }
            h1 { color: #2563eb; font-size: 32px; border-bottom: 2px solid #e5e7eb; padding-bottom: 20px; }
            .content { font-size: 14px; line-height: 1.8; }
            pre { background: #f3f4f6; padding: 15px; border-radius: 8px; }
        </style>
    </head>
    <body>
        <h1>${data.title}</h1>
        <div class="content">
            ${mdToHtml(data.content)}
        </div>
        <div style="margin-top: 50px; text-align: center; color: #9ca3af; font-size: 12px;">
            Generated by Actinova AI Tutor
        </div>
    </body>
    </html>`;
};

export async function POST(req) {
    try {
        const body = await req.json();
        const { type, data } = body;

        let html = "";
        if (type === 'course') {
            html = generateCourseHtml(data);
        } else if (type === 'lesson') {
            html = generateLessonHtml(data);
        } else {
            return NextResponse.json({ error: "Invalid PDF type" }, { status: 400 });
        }

        const browser = await puppeteer.launch({
            headless: true,
            args: ['--no-sandbox', '--disable-setuid-sandbox']
        });

        const page = await browser.newPage();
        await page.setContent(html, { waitUntil: 'networkidle0' });

        const pdfBuffer = await page.pdf({
            format: 'A4',
            printBackground: true,
            margin: { top: '20mm', bottom: '20mm', left: '20mm', right: '20mm' },
            displayHeaderFooter: true,
            headerTemplate: '<div style="font-size:10px; margin:0 20px; color:#9ca3af;">Actinova AI Tutor</div>',
            footerTemplate: '<div style="font-size:10px; margin:0 20px; width:100%; text-align:right; color:#9ca3af;">Page <span class="pageNumber"></span> of <span class="totalPages"></span></div>'
        });

        await browser.close();

        return new NextResponse(pdfBuffer, {
            headers: {
                'Content-Type': 'application/pdf',
                'Content-Disposition': `attachment; filename="${(data.title || 'document').replace(/\s+/g, '_')}.pdf"`
            }
        });

    } catch (error) {
        console.error("Puppeteer PDF Error:", error);
        return NextResponse.json({ error: "Failed to generate PDF" }, { status: 500 });
    }
}
